import { BookInfo } from "./types";

export const bibleBookMap: Record<string, BookInfo> = {
  "sa": { bookId: 1, bookName: { vi: "Sáng-thế Ký", en: "Genesis" } },
  "xu": { bookId: 2, bookName: { vi: "Xuất Ê-díp-tô Ký", en: "Exodus" } },
  "le": { bookId: 3, bookName: { vi: "Lê-vi Ký", en: "Leviticus" } },
  "dan": { bookId: 4, bookName: { vi: "Dân-số Ký", en: "Numbers" } },
  "phu": { bookId: 5, bookName: { vi: "Phục-truyền Luật-lệ Ký", en: "Deuteronomy" } },
  "gios": { bookId: 6, bookName: { vi: "Giô-suê", en: "Joshua" } },
  "cac": { bookId: 7, bookName: { vi: "Các Quan Xét", en: "Judges" } },
  "ru": { bookId: 8, bookName: { vi: "Ru-tơ", en: "Ruth" } },
  "1sa": { bookId: 9, bookName: { vi: "1 Sa-mu-ên", en: "1 Samuel" } },
  "2sa": { bookId: 10, bookName: { vi: "2 Sa-mu-ên", en: "2 Samuel" } },
  "1vua": { bookId: 11, bookName: { vi: "1 Các Vua", en: "1 Kings" } },
  "2vua": { bookId: 12, bookName: { vi: "2 Các Vua", en: "2 Kings" } },
  "1su": { bookId: 13, bookName: { vi: "1 Sử-ký", en: "1 Chronicles" } },
  "2su": { bookId: 14, bookName: { vi: "2 Sử-ký", en: "2 Chronicles" } },
  "exo": { bookId: 15, bookName: { vi: "E-xơ-ra", en: "Ezra" } },
  "ne": { bookId: 16, bookName: { vi: "Nê-hê-mi", en: "Nehemiah" } },
  "et": { bookId: 17, bookName: { vi: "Ê-xơ-tê", en: "Esther" } },
  "giop": { bookId: 18, bookName: { vi: "Gióp", en: "Job" } },
  "thi": { bookId: 19, bookName: { vi: "Thi-thiên", en: "Psalms" } },
  "ch": { bookId: 20, bookName: { vi: "Châm-ngôn", en: "Proverbs" } },
  "tr": { bookId: 21, bookName: { vi: "Truyền-đạo", en: "Ecclesiastes" } },
  "nha": { bookId: 22, bookName: { vi: "Nhã-ca", en: "Song of Solomon" } },
  "es": { bookId: 23, bookName: { vi: "Ê-sai", en: "Isaiah" } },
  "gie": { bookId: 24, bookName: { vi: "Giê-rê-mi", en: "Jeremiah" } },
  "ca": { bookId: 25, bookName: { vi: "Ca-thương", en: "Lamentations" } },
  "exe": { bookId: 26, bookName: { vi: "Ê-xê-chi-ên", en: "Ezekiel" } },
  "da": { bookId: 27, bookName: { vi: "Đa-ni-ên", en: "Daniel" } },
  "os": { bookId: 28, bookName: { vi: "Ô-sê", en: "Hosea" } },
  "gio": { bookId: 29, bookName: { vi: "Giô-ên", en: "Joel" } },
  "am": { bookId: 30, bookName: { vi: "A-mốt", en: "Amos" } },
  "ap": { bookId: 31, bookName: { vi: "Áp-đia", en: "Obadiah" } },
  "gion": { bookId: 32, bookName: { vi: "Giô-na", en: "Jonah" } },
  "mi": { bookId: 33, bookName: { vi: "Mi-chê", en: "Micah" } },
  "na": { bookId: 34, bookName: { vi: "Na-hôm", en: "Nahum" } },
  "ha": { bookId: 35, bookName: { vi: "Ha-ba-cúc", en: "Habakkuk" } },
  "so": { bookId: 36, bookName: { vi: "Xô-phô-ni", en: "Zephaniah" } },
  "ag": { bookId: 37, bookName: { vi: "A-ghê", en: "Haggai" } },
  "xa": { bookId: 38, bookName: { vi: "Xa-cha-ri", en: "Zechariah" } },
  "ma": { bookId: 39, bookName: { vi: "Ma-la-chi", en: "Malachi" } },
  "mat": { bookId: 40, bookName: { vi: "Ma-thi-ơ", en: "Matthew" } },
  "mac": { bookId: 41, bookName: { vi: "Mác", en: "Mark" } },
  "lu": { bookId: 42, bookName: { vi: "Lu-ca", en: "Luke" } },
  "gi": { bookId: 43, bookName: { vi: "Giăng", en: "John" } },
  "cong": { bookId: 44, bookName: { vi: "Công-vụ các Sứ-đồ", en: "Acts" } },
  "ro": { bookId: 45, bookName: { vi: "Rô-ma", en: "Romans" } },
  "1co": { bookId: 46, bookName: { vi: "1 Cô-rinh-tô", en: "1 Corinthians" } },
  "2co": { bookId: 47, bookName: { vi: "2 Cô-rinh-tô", en: "2 Corinthians" } },
  "ga": { bookId: 48, bookName: { vi: "Ga-la-ti", en: "Galatians" } },
  "eph": { bookId: 49, bookName: { vi: "Ê-phê-sô", en: "Ephesians" } },
  "phi": { bookId: 50, bookName: { vi: "Phi-líp", en: "Philippians" } },
  "co": { bookId: 51, bookName: { vi: "Cô-lô-se", en: "Colossians" } },
  "1te": { bookId: 52, bookName: { vi: "1 Tê-sa-lô-ni-ca", en: "1 Thessalonians" } },
  "2te": { bookId: 53, bookName: { vi: "2 Tê-sa-lô-ni-ca", en: "2 Thessalonians" } },
  "1ti": { bookId: 54, bookName: { vi: "1 Ti-mô-thê", en: "1 Timothy" } },
  "2ti": { bookId: 55, bookName: { vi: "2 Ti-mô-thê", en: "2 Timothy" } },
  "tit": { bookId: 56, bookName: { vi: "Tít", en: "Titus" } },
  "phil": { bookId: 57, bookName: { vi: "Phi-lê-môn", en: "Philemon" } },
  "he": { bookId: 58, bookName: { vi: "Hê-bơ-rơ", en: "Hebrews" } },
  "gia": { bookId: 59, bookName: { vi: "Gia-cơ", en: "James" } },
  "1phi": { bookId: 60, bookName: { vi: "1 Phi-e-rơ", en: "1 Peter" } },
  "2phi": { bookId: 61, bookName: { vi: "2 Phi-e-rơ", en: "2 Peter" } },
  "1gi": { bookId: 62, bookName: { vi: "1 Giăng", en: "1 John" } },
  "2gi": { bookId: 63, bookName: { vi: "2 Giăng", en: "2 John" } },
  "3gi": { bookId: 64, bookName: { vi: "3 Giăng", en: "3 John" } },
  "giu": { bookId: 65, bookName: { vi: "Giu-đe", en: "Jude" } },
  "kh": { bookId: 66, bookName: { vi: "Khải-huyền", en: "Revelation" } }
};
